#! /bin/sh

#
# makehtml.sh
#
# Convert .md files into .html for viewing with a web browser
#
# multimarkdown's output is naked HTML with no <head> or <body> tags
# so we wrap that in a simple template.
#
# Copyright (c) 2025 by Martin Guy <martinwguy@gmail.com>
# This code is in the public domain.
#

usage() {
    echo 'Usage: $0 file.md'
}

# Use printf instead of echo as it is more portable.
echo() {
    local nflag

    nflag=false
    case "$1" in
    -n) nflag=true; shift ;;
    esac

    printf "%s" "$*"
    $nflag || printf '\n'
}

echo '' | multimarkdown > /dev/null || {
    {
	echo "You need to install multimarkdown to run makehtml.sh"
	echo "Fedora/Red Hat/Centos: yum install multimarkdown"
	echo "Debian/Ubuntu/Mint: apt install libtext-multimarkdown-perl"
	echo "or get the latest version from"
	echo "https://fletcherpenney.net/multimarkdown" or
	echo "https://github.com/fletcher/MultiMarkdown-6/releases"
    } 1>&2
    exit 1
}

makehtml() {
    local mdfile number state milestone labels
    local title ftitle htitle utitle
    local file hfile ufile size type

    for mdfile in "$@"
    do
	test ! -f "$mdfile" && continue
	{
	    echo "<html><head>"
	    echo "<title>Miranda manual</title>"
	    echo "</head><body>"

	    cat "$mdfile" | multimarkdown

	    echo "<hr>Generated by <a href=\"https://codeberg.org/sox_ng/sox_ng/src/branch/main/issues/makehtml.sh\"><TT>makehtml.sh</TT></a> on $(LANG=C date -u)"
	    echo "</body></html>"
	} > "$(echo "$mdfile" | sed 's/\.md$//').html"
    done
}

makehtml "$@"
