#! /bin/sh

# quote info about the compiling host so that it can be included
# in a -D line to cc.

# All this hairiness is to make it work on a variety of different /bin/sh
# whose "echo"s do or don't interpret \escape sequences and
# whose "sed"s can or cannot handle the last line not having a newline.

{ {
    echo compiled: `date`
    make -s tellcc
    cat .host
  } | sed 's/$/\\/' | tr '\n' n; echo ''
} | sed 's/.*/"&"/'
